# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    player.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', username: 'exact' } ]
        tags: ['api_platform.filter']
